name: Release package

on:
  workflow_call:
    inputs:
      NODE_VERSION:
        type: string
        required: true
      NODE_CACHE_KEY:
        type: string
        required: true

    secrets:
      SEMANTIC_RELEASE_NPM_TOKEN:
        required: true
      SEMANTIC_RELEASE_GH_TOKEN:
        required: true

jobs:
  test:
    name: Release package
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

      - name: Load dependencies from cache
        uses: actions/cache@5a3ec84eff668545956fd18022155c47e93e2684 # v4
        with:
          path: node_modules
          key: ${{ inputs.NODE_CACHE_KEY }}

      - name: Setup node
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4
        with:
          node-version: '${{ inputs.NODE_VERSION }}'

      - name: Run build
        run: npm run build

      - name: Run release
        run: npm run release
        env:
          NPM_TOKEN: ${{ secrets.SEMANTIC_RELEASE_NPM_TOKEN }}
          GH_TOKEN: ${{ secrets.SEMANTIC_RELEASE_GH_TOKEN }}
