name: Test and Release

on:
  push:
    branches: [ master, main ]

env:
  NPM_TOKEN: ${{ secrets.SEMANTIC_RELEASE_NPM_TOKEN1 }}
  GH_TOKEN: ${{ secrets.SEMANTIC_RELEASE_GH_TOKEN1 }}

jobs:
  init:
    name: Init
    uses: ./.github/workflows/_init.yml
