name: Test and Release

on:
  push:
    branches:
      - master
      - main

env:
  NPM_TOKEN: ${{ secrets.SEMANTIC_RELEASE_NPM_TOKEN }}
  GH_TOKEN: ${{ secrets.SEMANTIC_RELEASE_GH_TOKEN }}

jobs:
  init:
    name: Init
    uses: ./.github/workflows/_init.yml

  test:
    name: Test
    uses: ./.github/workflows/_test.yml
    needs: [ init ]
    with:
      NODE_VERSION: ${{ needs.init.outputs.NODE_VERSION }}
      NODE_CACHE_KEY: ${{ needs.init.outputs.NODE_CACHE_KEY }}

  deploy:
    name: Test
    uses: ./.github/workflows/_deploy.yml
    needs: [ init, test ]
    with:
      NODE_VERSION: ${{ needs.init.outputs.NODE_VERSION }}
      NODE_CACHE_KEY: ${{ needs.init.outputs.NODE_CACHE_KEY }}
